-- MySQL Script generated by MySQL Workbench
-- 08/31/17 15:03:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema puerto_rico
-- -----------------------------------------------------

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP SCHEMA IF EXISTS `puerto_rico` ;
CREATE SCHEMA IF NOT EXISTS `puerto_rico` ;
USE `puerto_rico` ;

-- -----------------------------------------------------
-- Table `puerto_rico`.`subjects_ids`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puerto_rico`.`subjects_ids` (
  `project_id` VARCHAR(45) NOT NULL,
  `rds_id` VARCHAR(45) NULL,
  `unique_id` VARCHAR(45) NULL,
  PRIMARY KEY (`project_id`),
  UNIQUE INDEX `project_id_UNIQUE` (`project_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `puerto_rico`.`p1_screenings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puerto_rico`.`p1_screenings` (
  `rds_id` INT UNSIGNED NOT NULL,
  `project_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rds_id`),
  UNIQUE INDEX `project_id_UNIQUE` (`project_id` ASC),
  UNIQUE INDEX `rds_id_UNIQUE` (`rds_id` ASC),
  CONSTRAINT `p1_screenings_project_id`
    FOREIGN KEY (`project_id`)
    REFERENCES `puerto_rico`.`subjects_ids` (`project_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `puerto_rico`.`p1_hivs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puerto_rico`.`p1_hivs` (
  `rds_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`rds_id`),
  UNIQUE INDEX `coupon_id_UNIQUE` (`rds_id` ASC),
  CONSTRAINT `p1_hivs_rds_id`
    FOREIGN KEY (`rds_id`)
    REFERENCES `puerto_rico`.`p1_screenings` (`rds_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `puerto_rico`.`p1_hcvs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puerto_rico`.`p1_hcvs` (
  `rds_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`rds_id`),
  UNIQUE INDEX `coupon_id_UNIQUE` (`rds_id` ASC),
  CONSTRAINT `p1_hcvs_rds_id`
    FOREIGN KEY (`rds_id`)
    REFERENCES `puerto_rico`.`p1_screenings` (`rds_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `puerto_rico`.`p1_interviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puerto_rico`.`p1_interviews` (
  `rds_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`rds_id`),
  UNIQUE INDEX `coupon_id_UNIQUE` (`rds_id` ASC),
  CONSTRAINT `p1_interviews_rds_id`
    FOREIGN KEY (`rds_id`)
    REFERENCES `puerto_rico`.`p1_screenings` (`rds_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `puerto_rico`.`p1_followups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puerto_rico`.`p1_followups` (
  `rds_id` INT UNSIGNED NOT NULL,
  `LtCallDt` DATE NOT NULL,
  `LtCallST` TIME NOT NULL,
  PRIMARY KEY (`rds_id`, `LtCallDt`, `LtCallST`),
  CONSTRAINT `p1_followups_rds_id`
    FOREIGN KEY (`rds_id`)
    REFERENCES `puerto_rico`.`p1_screenings` (`rds_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `puerto_rico`.`p2_network_supplement_edges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puerto_rico`.`p2_network_supplement_edges` (
  `full_edge_id` VARCHAR(45) NOT NULL,
  `sender_id` VARCHAR(45) NOT NULL,
  `receiver_id` VARCHAR(45) NOT NULL,
  `unique_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`unique_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `puerto_rico`.`p2_hivs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puerto_rico`.`p2_hivs` (
  `unique_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`unique_id`),
  UNIQUE INDEX `unique_id_UNIQUE` (`unique_id` ASC),
  CONSTRAINT `p2_hivs_unique_id`
    FOREIGN KEY (`unique_id`)
    REFERENCES `puerto_rico`.`p2_network_supplement_edges` (`unique_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `puerto_rico`.`p2_hcvs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puerto_rico`.`p2_hcvs` (
  `unique_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`unique_id`),
  UNIQUE INDEX `unique_id_UNIQUE` (`unique_id` ASC),
  CONSTRAINT `p2_hcvs_unique_id`
    FOREIGN KEY (`unique_id`)
    REFERENCES `puerto_rico`.`p2_network_supplement_edges` (`unique_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `puerto_rico`.`p2_first_interviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puerto_rico`.`p2_first_interviews` (
  `unique_id` VARCHAR(45) NOT NULL,
  `project_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`unique_id`),
  UNIQUE INDEX `unique_id_UNIQUE` (`unique_id` ASC),
  UNIQUE INDEX `project_id_UNIQUE` (`project_id` ASC),
  CONSTRAINT `p2_first_interviews_unique_id`
    FOREIGN KEY (`unique_id`)
    REFERENCES `puerto_rico`.`p2_network_supplement_edges` (`unique_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `p2_first_interviews_project_id`
    FOREIGN KEY (`project_id`)
    REFERENCES `puerto_rico`.`subjects_ids` (`project_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `puerto_rico`.`p2_second_interviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puerto_rico`.`p2_second_interviews` (
  `unique_id` VARCHAR(45) NOT NULL,
  `rds_id` INT UNSIGNED NULL,
  PRIMARY KEY (`unique_id`),
  UNIQUE INDEX `unique_id_UNIQUE` (`unique_id` ASC),
  INDEX `rds_id_idx` (`rds_id` ASC),
  CONSTRAINT `p2_second_interviews_unique_id`
    FOREIGN KEY (`unique_id`)
    REFERENCES `puerto_rico`.`p2_network_supplement_edges` (`unique_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `p2_second_interviews_rds_id`
    FOREIGN KEY (`rds_id`)
    REFERENCES `puerto_rico`.`p1_screenings` (`rds_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `puerto_rico`.`p1_p2_overlaps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puerto_rico`.`p1_p2_overlaps` (
  `unique_id` VARCHAR(45) NOT NULL,
  `rds_id` INT UNSIGNED NOT NULL,
  `project_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`unique_id`, `rds_id`, `project_id`),
  INDEX `coupon_id_idx` (`rds_id` ASC),
  UNIQUE INDEX `coupon_id_UNIQUE` (`rds_id` ASC),
  UNIQUE INDEX `unique_id_UNIQUE` (`unique_id` ASC),
  UNIQUE INDEX `project_id_UNIQUE` (`project_id` ASC),
  CONSTRAINT `p1_p2_overlap_unique_id`
    FOREIGN KEY (`unique_id`)
    REFERENCES `puerto_rico`.`p2_network_supplement_edges` (`unique_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `p1_p2_overlap_rds_id`
    FOREIGN KEY (`rds_id`)
    REFERENCES `puerto_rico`.`p1_screenings` (`rds_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `p1_p2_overlap_project_id`
    FOREIGN KEY (`project_id`)
    REFERENCES `puerto_rico`.`subjects_ids` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `puerto_rico`.`all_edges_index`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puerto_rico`.`all_edges_index` (
  `edge_id` VARCHAR(45) NOT NULL,
  `sender_pid` VARCHAR(45) NOT NULL,
  `receiver_pid` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`edge_id`),
  UNIQUE INDEX `id_UNIQUE` (`edge_id` ASC),
  INDEX `sender_pid_idx` (`sender_pid` ASC),
  INDEX `receiver_pid_idx` (`receiver_pid` ASC),
  CONSTRAINT `edges_sender_pid`
    FOREIGN KEY (`sender_pid`)
    REFERENCES `puerto_rico`.`subjects_ids` (`project_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `edges_receiver_pid`
    FOREIGN KEY (`receiver_pid`)
    REFERENCES `puerto_rico`.`subjects_ids` (`project_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `puerto_rico`.`network_edges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puerto_rico`.`network_edges` (
  `edge_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`edge_id`),
  UNIQUE INDEX `edge_id_UNIQUE` (`edge_id` ASC),
  CONSTRAINT `network_edges_edge_id`
    FOREIGN KEY (`edge_id`)
    REFERENCES `puerto_rico`.`all_edges_index` (`edge_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `puerto_rico`.`rds_edges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puerto_rico`.`rds_edges` (
  `edge_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`edge_id`),
  UNIQUE INDEX `edge_id_UNIQUE` (`edge_id` ASC),
  CONSTRAINT `rds_edges_edge_id`
    FOREIGN KEY (`edge_id`)
    REFERENCES `puerto_rico`.`all_edges_index` (`edge_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `puerto_rico`.`all_notes_index`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puerto_rico`.`all_notes_index` (
  `note_id` INT UNSIGNED NOT NULL,
  `note_name` VARCHAR(45) NOT NULL,
  `date` DATE NULL,
  `note_type` VARCHAR(255) NOT NULL COMMENT 'May be \"F\" for field note, \"C\" for connection note, \"R\" for Roberto',
  `text` LONGTEXT NULL,
  PRIMARY KEY (`note_id`),
  UNIQUE INDEX `note_name_UNIQUE` (`note_name` ASC),
  UNIQUE INDEX `note_id_UNIQUE` (`note_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `puerto_rico`.`edges_to_notes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puerto_rico`.`edges_to_notes` (
  `note_edge_id` INT UNSIGNED ZEROFILL NOT NULL,
  `edge_id` VARCHAR(45) NOT NULL,
  `note_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`note_edge_id`),
  UNIQUE INDEX `id_UNIQUE` (`note_edge_id` ASC),
  INDEX `edge_id_idx` (`edge_id` ASC),
  CONSTRAINT `note_edges_edge_id`
    FOREIGN KEY (`edge_id`)
    REFERENCES `puerto_rico`.`all_edges_index` (`edge_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `note_edges_note_id`
    FOREIGN KEY (`note_id`)
    REFERENCES `puerto_rico`.`all_notes_index` (`note_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `puerto_rico`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puerto_rico`.`authors` (
  `author_id` INT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`author_id`),
  UNIQUE INDEX `author_id_UNIQUE` (`author_id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
